import { HttpResponse } from '.';

export interface LoginForm {
  username: string;
  password: string;
  rememberMe: boolean;
  code: string;
  uuid: string;
}

// Generated by https://quicktype.io

export interface UserInfoHttpResponse<T> extends HttpResponse<T> {
  permissions: string[];
  roles: string[];
  user: UserInfo;
}

export interface UserInfo {
  searchValue: null;
  createBy: string;
  createTime: string;
  updateBy: null;
  updateTime: null;
  remark: null;
  params: Params;
  userId: number;
  deptId: number;
  userName: string;
  nickName: string;
  email: string;
  phonenumber: string;
  sex: string;
  avatar: string;
  salt: null;
  status: string;
  delFlag: string;
  loginIp: string;
  loginDate: null;
  dept: Dept;
  roles: Role[];
  roleIds: null;
  postIds: null;
  admin: boolean;
}

export interface Dept {
  searchValue: null;
  createBy: null;
  createTime: null;
  updateBy: null;
  updateTime: null;
  remark: null;
  deptId: number;
  parentId: number;
  ancestors: null;
  deptName: string;
  orderNum: string;
  leader: string;
  phone: null;
  email: null;
  status: string;
  delFlag: null;
  parentName: null;
  children: any[];
}

export interface Role {
  searchValue: null;
  createBy: null;
  createTime: null;
  updateBy: null;
  updateTime: null;
  remark: null;
  params: Params;
  roleId: number;
  roleName: string;
  roleKey: string;
  roleSort: string;
  dataScope: string;
  menuCheckStrictly: boolean;
  deptCheckStrictly: boolean;
  status: string;
  delFlag: null;
  flag: boolean;
  menuIds: null;
  deptIds: null;
  admin: boolean;
}
